import {
  ColumnType,
  Generated,
  Insertable,
  Selectable,
  Transaction,
  Updateable,
} from "kysely";
import { MoodValue } from "@/common/types.js";

export interface Database {
  // `moods` is the name of the table.
  // Table names can be singular or plural, but they should be
  // consistent throughout the application.
  moods: MoodTable;
  users: UserTable;
}

// This interface describes the `mood` table to Kysely. Table
// interfaces should only be used in the `Database` type above
// and never as a result type of a query!. See the `Mood`,
// `NewMood` and `MoodUpdate` types below.
export interface MoodTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: string;

  mood: MoodValue;

  // If the column is nullable in the database, make its type nullable.
  // Don't use optional properties. Optionality is always determined
  // automatically by Kysely.
  note: string | null;

  // You can specify a different type for each operation (select, insert and
  // update) using the `ColumnType<SelectType, InsertType, UpdateType>`
  // wrapper. Here we define a column `created_at` that is selected as
  // a `Date`, can optionally be provided as a `string` in inserts and
  // can never be updated:
  created_at: ColumnType<Date, string | undefined, never>;

  // You can specify JSON columns using the `JSONColumnType` wrapper.
  // It is a shorthand for `ColumnType<T, string, string>`, where T
  // is the type of the JSON object/array retrieved from the database,
  // and the insert and update types are always `string` since you're
  // always stringifying insert/update values.
  /*   metadata: JSONColumnType<{
    login_at: string;
    ip: string | null;
    agent: string | null;
    plan: "free" | "premium";
  }>; */

  updated_at: ColumnType<Date, string | undefined, string | undefined>;
  deleted_at: ColumnType<Date | null, string | null, string | null>;
}

// You should not use the table schema interfaces directly. Instead, you should
// use the `Selectable`, `Insertable` and `Updateable` wrappers. These wrappers
// make sure that the correct types are used in each operation.
//
// Most of the time you should trust the type inference and not use explicit
// types at all. These types can be useful when typing function arguments.
export type Mood = Selectable<MoodTable>;
export type NewMood = Insertable<MoodTable>;
export type MoodUpdate = Updateable<MoodTable>;

export interface UserTable {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  is_admin: boolean;
  approved: boolean;
  created_at: ColumnType<Date, string | undefined, string | undefined>;
  updated_at: ColumnType<Date, string | undefined, string | undefined>;
}

export type User = Selectable<UserTable>;
export type NewUser = Insertable<UserTable>;
export type UserUpdate = Updateable<UserTable>;

export type KyselyTransaction = Transaction<Database>;
